---
openapi: 3.0.3
info:
  title: Catalog API
  version: 1.0.0
servers:
- url: https://${{values.component_id}}-${{values.namespace}}${{values.cluster}}/
  description: (RHDH component deployment)
- url: http://localhost:8080
  description: (localhost development / testing)
paths:
  /api/catalog:
    get:
      tags:
      - Example catalog
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string