apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.component_id}}
  annotations: 
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"{{ .Values.app.namespace }}-catalog-spring"},{"apiVersion":"apps/v1","kind":"Deployment","name":"{{ .Values.app.namespace }}-inventory-quarkus"}]'
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
    {{- include "quarkus-template.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: coolstore-demo
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "quarkus-template.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backstage.labels" . | nindent 8 }}
        {{- include "quarkus-template.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "quarkus-template.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "quarkus-template.image" . }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP          
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: COMPONENT_CATALOG_HOST
              value: {{ .Values.app.namespace }}-catalog-spring
            - name: COMPONENT_INVENTORY_HOST
              value: {{ .Values.app.namespace }}-inventory-quarkus
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
